# Production profile
logging:
  level:
    io.github.syakuis: info
    org.hibernate.sql: off
    org.hibernate.type.descriptor.sql.BasicBinder: off
    org.hibernate.type.descriptor.sql.BasicExtractor: off
  file:
    path: /var/authorization-server/logs
spring:
  main:
    banner-mode: console
  devtools:
    livereload:
      enabled: false
  datasource:
    initialization-mode: never
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url:
      username:
      password:
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
authorization:
  oauth2:
    jwt:
      jks-location: file:/var/authorization/certificate/authorization.jks